In [51]:
import numpy as np


In [52]:
a=np.array([1.2,1.3,1.4], dtype=float)

In [53]:
print(a)

[1.2 1.3 1.4]


In [54]:
a.ndim

1

In [55]:
b=np.array([[1,2,3],[2,5,4],[2,1,3],[3,2,5]])

In [56]:
b.ndim

2

In [57]:
b

array([[1, 2, 3],
       [2, 5, 4],
       [2, 1, 3],
       [3, 2, 5]])

In [58]:
a.shape

(3,)

In [59]:
b.shape

(4, 3)

In [60]:
b.dtype

dtype('int32')

In [61]:
a.dtype

dtype('float64')

In [62]:
b[0][1]

2

In [63]:
b[0,:]

array([1, 2, 3])

In [64]:
b[:,0]

array([1, 2, 2, 3])

In [65]:
b[0,1]=10

In [66]:
b


array([[ 1, 10,  3],
       [ 2,  5,  4],
       [ 2,  1,  3],
       [ 3,  2,  5]])

In [67]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [68]:
np.ones((3,3), dtype='int32')

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [69]:
np.full((3,3),50, dtype='float')

array([[50., 50., 50.],
       [50., 50., 50.],
       [50., 50., 50.]])

In [70]:
np.random.rand(3,3)

array([[0.40853177, 0.68882417, 0.4854361 ],
       [0.38658195, 0.60338101, 0.4127028 ],
       [0.97820612, 0.27324962, 0.98977877]])

In [71]:
np.random.randint(-4,4, size=(3,3))

array([[-3,  1, -3],
       [-4, -2, -3],
       [-3, -2, -2]])

In [72]:
np.identity(3, dtype='int')

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [73]:
a= np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])


Extract all the first 3 rows of the last 5 columns in a given numpy 2D array ‘a’?

In [74]:
a[ :3,-5:]

array([[ 2,  3,  4,  5,  6],
       [20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12]])

Given a positive number 'n' greater than 2, create a NumPy array of size (nxn) with all zeros and ones such that the ones make a shape of "+"

Examples:

Input 1:

3

Output 1:

[[0 1 0]

[1 1 1]

[0 1 0]]

Input 2:

5

Output 1:

[[0 0 1 0 0]

[0 0 1 0 0]

[1 1 1 1 1]

[0 0 1 0 0]

[0 0 1 0 0]]

In [75]:
n=int(input(''))
a=np.zeros((n,n), dtype='int32')
a[n//2,:]=1
a[:,n//2]=1
a

5


array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [76]:
a

array([[0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0],
       [1, 1, 1, 1, 1],
       [0, 0, 1, 0, 0],
       [0, 0, 1, 0, 0]])

In [77]:
a=np.array([[1,2,3,4,5,6],
             [10,20,30,40,50,60],
             [12,12,12,12,12,12],
             [11,21,31,41,51,61],
             [13,24,34,44,54,64]])

In [78]:
a.ndim

2

In [79]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [12, 12, 12, 12, 12, 12],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [80]:
a[4//2,:]

array([12, 12, 12, 12, 12, 12])

In [81]:
a[5//2,:]=1

In [82]:
a

array([[ 1,  2,  3,  4,  5,  6],
       [10, 20, 30, 40, 50, 60],
       [ 1,  1,  1,  1,  1,  1],
       [11, 21, 31, 41, 51, 61],
       [13, 24, 34, 44, 54, 64]])

In [83]:
a[:,6//2]

array([ 4, 40,  1, 41, 44])

In [86]:
a[:,6//2]=1

In [87]:
a

array([[ 1,  2,  3,  1,  5,  6],
       [10, 20, 30,  1, 50, 60],
       [ 1,  1,  1,  1,  1,  1],
       [11, 21, 31,  1, 51, 61],
       [13, 24, 34,  1, 54, 64]])

# Arithmatic Operations using nupy

In [88]:
a = np.array([1,2,3,4])

In [89]:
a

array([1, 2, 3, 4])

In [90]:
a.min()

1

In [91]:
a=a+2

In [92]:
a

array([3, 4, 5, 6])

In [93]:
a=a**2

In [94]:
a

array([ 9, 16, 25, 36], dtype=int32)

In [96]:
np.min(a)

9

In [97]:
a.max()

36

In [98]:
a.mean()

21.5

In [107]:
a = np.array([[1,2,3,4], [5,6,7,8]])

In [114]:
a

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [108]:
a.ndim

2

In [109]:
a.min()

1

In [110]:
a.sum()

36

In [111]:
np.max(a)

8

In [112]:
np.max(a,axis=1)

array([4, 8])

In [113]:
np.max(a,axis=0)

array([5, 6, 7, 8])

In [115]:
np.sort(a,axis=0)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [117]:
np.sort(a,axis=1)

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [118]:
np.min(a,axis=0)

array([1, 2, 3, 4])

In [119]:
np.sum(a,axis=1)

array([10, 26])

In [121]:
np.sum(a,axis=0)

array([ 6,  8, 10, 12])